# Build configuration for ZMK Corne Mini Custom Shield
---
include:
  - board: nice_nano_v2
    shield: corne_custom_left
  - board: nice_nano_v2
    shield: corne_custom_right
  - board: nice_nano_v2
    shield: settings_reset
